# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1387, 880)
        MainWindow.setStyleSheet("background-color: rgb(255, 199, 229);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 681, 841))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 110, 651, 701))
        self.plainTextEdit.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 80, 121, 16))
        self.label.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 80, 101, 21))
        self.pushButton_5.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"楷体\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(160, 10, 501, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.label_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 121, 16))
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 40, 371, 20))
        self.lineEdit_2.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(560, 40, 101, 21))
        self.pushButton_6.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"楷体\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(250, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 21, 181))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(20, 490, 21, 181))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 20, 91, 31))
        self.pushButton_7.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"font: 14pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"楷体\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(180, 20, 91, 31))
        self.pushButton_8.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"楷体\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(290, 20, 81, 31))
        self.pushButton_9.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"楷体\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setGeometry(QtCore.QRect(390, 20, 101, 31))
        self.pushButton_10.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"楷体\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(50, 70, 601, 291))
        self.plainTextEdit_2.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(77, 232, 29, 255), stop:1 rgba(255, 255, 255, 255));")
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(50, 400, 601, 371))
        self.plainTextEdit_3.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_11.setGeometry(QtCore.QRect(510, 20, 101, 31))
        self.pushButton_11.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"楷体\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_3, "")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(703, 50, 671, 791))
        self.textEdit.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1170, 10, 101, 31))
        self.pushButton_3.setStyleSheet("   background-color: rgb(0, 173, 0);\n"
"            color: rgb(255, 255, 255);\n"
"            font: 9pt \"楷体\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1300, 10, 75, 31))
        self.pushButton_4.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"楷体\";")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyqt开发的客户端"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>是很多时候</p></body></html>"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>大萨达</p></body></html>"))
        self.label.setText(_translate("MainWindow", "下面写python脚本"))
        self.pushButton_5.setText(_translate("MainWindow", "运行python代码"))
        self.label_2.setText(_translate("MainWindow", "python脚本全路径："))
        self.label_3.setText(_translate("MainWindow", "项目路径(PYTHONPATH)"))
        self.pushButton_6.setText(_translate("MainWindow", "运行python脚本"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "执行python"))
        self.pushButton.setText(_translate("MainWindow", "测试函数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "测试按钮的"))
        self.label_4.setText(_translate("MainWindow", "需要翻译的语句"))
        self.label_5.setText(_translate("MainWindow", "翻译的结果"))
        self.pushButton_7.setText(_translate("MainWindow", "百度翻译"))
        self.pushButton_8.setText(_translate("MainWindow", "google翻译"))
        self.pushButton_9.setText(_translate("MainWindow", "有道翻译"))
        self.pushButton_10.setText(_translate("MainWindow", "爱词霸翻译"))
        self.plainTextEdit_2.setPlaceholderText(_translate("MainWindow", "请输入需要翻译的语句，支持自动识别中英文"))
        self.plainTextEdit_3.setPlaceholderText(_translate("MainWindow", "请输入需要翻译的语句，支持自动识别中英文"))
        self.pushButton_11.setText(_translate("MainWindow", "全部翻译"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "翻译"))
        self.pushButton_3.setText(_translate("MainWindow", "暂停控制台"))
        self.pushButton_4.setText(_translate("MainWindow", "清除控制台"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
